import AVFoundation
import Core
import Foundation
@testable import MonthlyVideoGeneratorApp
import XCTest

@MainActor
final class MainWindowViewModelTests: XCTestCase {
    func testInitialOutputNameUsesTemporaryTestingFormat() {
        let viewModel = makeViewModel(
            coordinator: RenderCoordinatorSpy(preparation: makePreparation()),
            filenameGenerator: TemporaryTestingFilenameGenerator(now: { Date(timeIntervalSince1970: 1_700_000_000) }),
            preferencesStore: makePreferencesStore()
        )

        XCTAssertEqual(viewModel.outputFilename, "Testing - S2026E1700000000 - Smart - Smartfps - HDR")
        XCTAssertTrue(viewModel.isOutputNameAutoManaged)
    }

    func testOutputNameAutoSyncStopsAfterManualEditAndCanBeRestored() {
        let viewModel = makeViewModel(
            coordinator: RenderCoordinatorSpy(preparation: makePreparation()),
            filenameGenerator: TemporaryTestingFilenameGenerator(now: { Date(timeIntervalSince1970: 1_700_000_100) }),
            preferencesStore: makePreferencesStore()
        )

        viewModel.selectedResolutionPolicy = .fixed720p
        XCTAssertEqual(viewModel.outputFilename, "Testing - S2026E1700000100 - 720 - Smartfps - HDR")
        XCTAssertTrue(viewModel.isOutputNameAutoManaged)

        viewModel.outputFilename = "Manual Override"
        XCTAssertFalse(viewModel.isOutputNameAutoManaged)

        viewModel.selectedDynamicRange = .sdr
        XCTAssertEqual(viewModel.outputFilename, "Manual Override")

        viewModel.useAutoGeneratedOutputName()
        XCTAssertTrue(viewModel.isOutputNameAutoManaged)
        XCTAssertEqual(viewModel.outputFilename, "Testing - S2026E1700000100 - 720 - Smartfps - SDR")
    }

    func testStartRenderRegeneratesAutoManagedOutputNameAtRenderTime() async throws {
        let dateProvider = DateSequenceProvider([
            Date(timeIntervalSince1970: 1_700_000_000),
            Date(timeIntervalSince1970: 1_700_000_999)
        ])
        let coordinator = RenderCoordinatorSpy(preparation: makePreparation())
        let viewModel = makeViewModel(
            coordinator: coordinator,
            filenameGenerator: TemporaryTestingFilenameGenerator(now: dateProvider.next),
            preferencesStore: makePreferencesStore()
        )
        let directory = makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        viewModel.selectedFolderURL = directory
        viewModel.outputDirectoryURL = directory
        XCTAssertEqual(viewModel.outputFilename, "Testing - S2026E1700000000 - Smart - Smartfps - HDR")

        viewModel.startRender()
        await waitUntil(
            timeout: 2.0,
            message: "Timed out waiting for single render to finish."
        ) {
            coordinator.renderRequests.count == 1 && !viewModel.isRendering
        }

        XCTAssertEqual(viewModel.outputFilename, "Testing - S2026E1700000999 - Smart - Smartfps - HDR")
        XCTAssertEqual(coordinator.prepareFolderRequests.count, 1)
        XCTAssertEqual(coordinator.renderRequests.first?.output.baseFilename, "Testing - S2026E1700000999 - Smart - Smartfps - HDR")
    }

    func testMegaTestReusesPreparationAndIgnoresManualOutputNameField() async throws {
        let dateProvider = DateSequenceProvider([
            Date(timeIntervalSince1970: 1_700_000_000),
            Date(timeIntervalSince1970: 1_700_000_101),
            Date(timeIntervalSince1970: 1_700_000_102),
            Date(timeIntervalSince1970: 1_700_000_103),
            Date(timeIntervalSince1970: 1_700_000_104)
        ])
        let coordinator = RenderCoordinatorSpy(preparation: makePreparation())
        let viewModel = makeViewModel(
            coordinator: coordinator,
            filenameGenerator: TemporaryTestingFilenameGenerator(now: dateProvider.next),
            preferencesStore: makePreferencesStore()
        )
        let directory = makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        viewModel.selectedFolderURL = directory
        viewModel.outputDirectoryURL = directory
        viewModel.outputFilename = "Manual Override"
        viewModel.megaTestVaryResolution = true

        viewModel.startMegaTest()
        await waitUntil(
            timeout: 2.0,
            message: "Timed out waiting for mega test batch to finish."
        ) {
            coordinator.renderRequests.count == 4 && !viewModel.isRendering
        }

        XCTAssertEqual(coordinator.prepareFolderRequests.count, 1)
        XCTAssertEqual(coordinator.renderRequests.count, 4)
        XCTAssertFalse(coordinator.renderRequests.contains { $0.output.baseFilename == "Manual Override" })

        let generator = TemporaryTestingFilenameGenerator()
        let expectedNames = [
            generator.makeOutputName(resolution: .fixed720p, frameRate: .smart, dynamicRange: .hdr, date: Date(timeIntervalSince1970: 1_700_000_101)),
            generator.makeOutputName(resolution: .fixed1080p, frameRate: .smart, dynamicRange: .hdr, date: Date(timeIntervalSince1970: 1_700_000_102)),
            generator.makeOutputName(resolution: .fixed4K, frameRate: .smart, dynamicRange: .hdr, date: Date(timeIntervalSince1970: 1_700_000_103)),
            generator.makeOutputName(resolution: .smart, frameRate: .smart, dynamicRange: .hdr, date: Date(timeIntervalSince1970: 1_700_000_104))
        ]

        XCTAssertEqual(coordinator.renderRequests.map { $0.output.baseFilename }, expectedNames)
    }

    func testMegaTestCanStopAfterFailure() async throws {
        let coordinator = RenderCoordinatorSpy(preparation: makePreparation(), failedRenderIndices: [0])
        let viewModel = makeViewModel(
            coordinator: coordinator,
            filenameGenerator: TemporaryTestingFilenameGenerator(now: { Date(timeIntervalSince1970: 1_700_000_200) }),
            preferencesStore: makePreferencesStore()
        )
        let directory = makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        viewModel.selectedFolderURL = directory
        viewModel.outputDirectoryURL = directory
        viewModel.megaTestVaryRange = true

        viewModel.startMegaTest()
        await waitUntilFailurePrompt(viewModel)
        viewModel.stopMegaTestAfterFailure()
        await waitUntil(
            timeout: 2.0,
            message: "Timed out waiting for mega test stop flow to finish."
        ) {
            coordinator.renderRequests.count == 1 && !viewModel.isRendering
        }

        XCTAssertEqual(coordinator.renderRequests.count, 1)
        XCTAssertNil(viewModel.pendingMegaTestFailure)
        XCTAssertFalse(viewModel.showRenderCompleteAlert)
        XCTAssertTrue(viewModel.statusMessage.contains("Mega test stopped after failure"))
    }

    func testMegaTestCanContinueAfterFailure() async throws {
        let coordinator = RenderCoordinatorSpy(preparation: makePreparation(), failedRenderIndices: [0])
        let viewModel = makeViewModel(
            coordinator: coordinator,
            filenameGenerator: TemporaryTestingFilenameGenerator(now: { Date(timeIntervalSince1970: 1_700_000_300) }),
            preferencesStore: makePreferencesStore()
        )
        let directory = makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        viewModel.selectedFolderURL = directory
        viewModel.outputDirectoryURL = directory
        viewModel.megaTestVaryRange = true

        viewModel.startMegaTest()
        await waitUntilFailurePrompt(viewModel)
        viewModel.continueMegaTestAfterFailure()
        await waitUntil(
            timeout: 2.0,
            message: "Timed out waiting for mega test continue flow to finish."
        ) {
            coordinator.renderRequests.count == 2 && !viewModel.isRendering
        }

        XCTAssertEqual(coordinator.renderRequests.count, 2)
        XCTAssertNil(viewModel.pendingMegaTestFailure)
        XCTAssertTrue(viewModel.showRenderCompleteAlert)
        XCTAssertTrue(viewModel.statusMessage.contains("Mega test complete"))
    }

    private func makeViewModel(
        coordinator: RenderCoordinating,
        filenameGenerator: TemporaryTestingFilenameGenerator,
        preferencesStore: UserDefaults
    ) -> MainWindowViewModel {
        MainWindowViewModel(
            coordinator: coordinator,
            preferencesStore: preferencesStore,
            filenameGenerator: filenameGenerator
        )
    }

    private func makePreparation() -> RenderPreparation {
        let item = MediaItem(
            id: "image",
            type: .image,
            captureDate: Date(),
            duration: nil,
            pixelSize: CGSize(width: 1920, height: 1080),
            colorInfo: .unknown,
            locator: .file(URL(fileURLWithPath: "/tmp/image.jpg")),
            fileSizeBytes: 1_000,
            filename: "image.jpg"
        )
        let style = StyleProfile.stageOneDefault
        let timeline = TimelineBuilder().buildTimeline(
            items: [item],
            ordering: .captureDateAscendingStable,
            style: style
        )
        return RenderPreparation(items: [item], timeline: timeline, warnings: [])
    }

    private func makePreferencesStore() -> UserDefaults {
        let suiteName = "MainWindowViewModelTests.\(UUID().uuidString)"
        let defaults = UserDefaults(suiteName: suiteName) ?? .standard
        defaults.removePersistentDomain(forName: suiteName)
        return defaults
    }

    private func makeTemporaryDirectory() -> URL {
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        return directory
    }

    private func waitUntil(
        timeout: TimeInterval = 2.0,
        message: String,
        condition: @escaping () -> Bool
    ) async {
        let deadline = Date().addingTimeInterval(timeout)
        while !condition() && Date() < deadline {
            try? await Task.sleep(for: .milliseconds(10))
        }
        XCTAssertTrue(condition(), message)
    }

    private func waitUntilFailurePrompt(_ viewModel: MainWindowViewModel, timeout: TimeInterval = 2.0) async {
        let deadline = Date().addingTimeInterval(timeout)
        while viewModel.pendingMegaTestFailure == nil && Date() < deadline {
            try? await Task.sleep(for: .milliseconds(10))
        }
        XCTAssertNotNil(viewModel.pendingMegaTestFailure, "Timed out waiting for mega test failure prompt.")
    }
}

@MainActor
private final class RenderCoordinatorSpy: RenderCoordinating, @unchecked Sendable {
    let preparation: RenderPreparation
    let failedRenderIndices: Set<Int>
    private(set) var prepareFolderRequests: [RenderRequest] = []
    private(set) var renderRequests: [RenderRequest] = []
    private(set) var cancelCurrentRenderCallCount: Int = 0

    init(preparation: RenderPreparation, failedRenderIndices: Set<Int> = []) {
        self.preparation = preparation
        self.failedRenderIndices = failedRenderIndices
    }

    func prepareFolderRender(request: RenderRequest) async throws -> RenderPreparation {
        prepareFolderRequests.append(request)
        return preparation
    }

    func prepareFromItems(
        _ items: [MediaItem],
        request: RenderRequest,
        additionalWarnings: [String]
    ) -> RenderPreparation {
        RenderPreparation(
            items: items,
            timeline: preparation.timeline,
            warnings: preparation.warnings + additionalWarnings
        )
    }

    func render(
        preparation: RenderPreparation,
        request: RenderRequest,
        photoMaterializer: PhotoAssetMaterializing?,
        writeDiagnosticsLog: Bool,
        progressHandler: RenderProgressHandler,
        statusHandler: RenderStatusHandler
    ) async throws -> RenderResult {
        let index = renderRequests.count
        renderRequests.append(request)
        statusHandler?(writeDiagnosticsLog ? "Encoding with diagnostics" : "Encoding")
        progressHandler?(1.0)

        if failedRenderIndices.contains(index) {
            throw RenderError.exportFailed("Simulated failure \(index)")
        }

        let outputURL = request.output.directory
            .appendingPathComponent(request.output.baseFilename)
            .appendingPathExtension(request.export.container.fileExtension)
        return RenderResult(outputURL: outputURL, diagnosticsLogURL: nil, backendSummary: nil)
    }

    func cancelCurrentRender() {
        cancelCurrentRenderCallCount += 1
    }
}

private final class DateSequenceProvider: @unchecked Sendable {
    private let lock = NSLock()
    private var dates: [Date]

    init(_ dates: [Date]) {
        self.dates = dates
    }

    func next() -> Date {
        lock.lock()
        defer { lock.unlock() }
        guard !dates.isEmpty else {
            return Date(timeIntervalSince1970: 0)
        }
        if dates.count == 1 {
            return dates[0]
        }
        return dates.removeFirst()
    }
}
