import AVFoundation
import Core
import Foundation
@testable import MonthlyVideoGeneratorApp
import XCTest

@MainActor
final class MainWindowViewModelTests: XCTestCase {
    func testInitialOutputNameUsesTemporaryTestingFormat() {
        let viewModel = makeViewModel(
            coordinator: RenderCoordinatorSpy(preparation: makePreparation()),
            filenameGenerator: TemporaryTestingFilenameGenerator(now: { Date(timeIntervalSince1970: 1_700_000_000) }),
            preferencesStore: makePreferencesStore()
        )

        XCTAssertEqual(viewModel.outputFilename, "Testing - S2026E1700000000 - Smart - Smartfps - HDR - Smart")
        XCTAssertTrue(viewModel.isOutputNameAutoManaged)
    }

    func testOutputNameAutoSyncStopsAfterManualEditAndCanBeRestored() {
        let viewModel = makeViewModel(
            coordinator: RenderCoordinatorSpy(preparation: makePreparation()),
            filenameGenerator: TemporaryTestingFilenameGenerator(now: { Date(timeIntervalSince1970: 1_700_000_100) }),
            preferencesStore: makePreferencesStore()
        )

        viewModel.selectedResolutionPolicy = .fixed720p
        XCTAssertEqual(viewModel.outputFilename, "Testing - S2026E1700000100 - 720 - Smartfps - HDR - Smart")
        XCTAssertTrue(viewModel.isOutputNameAutoManaged)

        viewModel.outputFilename = "Manual Override"
        XCTAssertFalse(viewModel.isOutputNameAutoManaged)

        viewModel.selectedDynamicRange = .sdr
        XCTAssertEqual(viewModel.outputFilename, "Manual Override")

        viewModel.useAutoGeneratedOutputName()
        XCTAssertTrue(viewModel.isOutputNameAutoManaged)
        XCTAssertEqual(viewModel.outputFilename, "Testing - S2026E1700000100 - 720 - Smartfps - SDR - Smart")
    }

    func testStartRenderRegeneratesAutoManagedOutputNameAtRenderTime() async throws {
        let dateProvider = DateSequenceProvider([
            Date(timeIntervalSince1970: 1_700_000_000),
            Date(timeIntervalSince1970: 1_700_000_999)
        ])
        let coordinator = RenderCoordinatorSpy(preparation: makePreparation())
        let viewModel = makeViewModel(
            coordinator: coordinator,
            filenameGenerator: TemporaryTestingFilenameGenerator(now: dateProvider.next),
            preferencesStore: makePreferencesStore()
        )
        let directory = makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        viewModel.selectedFolderURL = directory
        viewModel.outputDirectoryURL = directory
        XCTAssertEqual(viewModel.outputFilename, "Testing - S2026E1700000000 - Smart - Smartfps - HDR - Smart")

        viewModel.startRender()
        await waitUntil(
            timeout: 2.0,
            message: "Timed out waiting for single render to finish."
        ) {
            coordinator.renderRequests.count == 1 && !viewModel.isRendering
        }

        XCTAssertEqual(viewModel.outputFilename, "Testing - S2026E1700000999 - Smart - Smartfps - HDR - Smart")
        XCTAssertEqual(coordinator.prepareFolderRequests.count, 1)
        XCTAssertEqual(coordinator.renderRequests.first?.output.baseFilename, "Testing - S2026E1700000999 - Smart - Smartfps - HDR - Smart")
    }

    func testSingleRenderCompletionSummaryListsRequestedAndActualExportOptions() async throws {
        let preparation = makePreparation(
            items: [
                makeVideoItem(
                    id: "video-1",
                    pixelSize: CGSize(width: 640, height: 360),
                    sourceFrameRate: 60,
                    sourceAudioChannelCount: 6
                )
            ]
        )
        let coordinator = RenderCoordinatorSpy(
            preparation: preparation,
            renderResultBuilder: { _, request, _ in
                let outputURL = request.output.directory
                    .appendingPathComponent(request.output.baseFilename)
                    .appendingPathExtension(request.export.container.fileExtension)
                return RenderResult(
                    outputURL: outputURL,
                    diagnosticsLogURL: nil,
                    backendSummary: "FFmpeg HDR backend [bundled] (encoder: hevcVideoToolbox)",
                    backendInfo: RenderBackendInfo(binarySource: .bundled, encoder: "hevcVideoToolbox"),
                    resolvedVideoInfo: ResolvedRenderVideoInfo(width: 1280, height: 720, frameRate: 60)
                )
            }
        )
        let viewModel = makeViewModel(
            coordinator: coordinator,
            filenameGenerator: TemporaryTestingFilenameGenerator(now: { Date(timeIntervalSince1970: 1_700_001_000) }),
            preferencesStore: makePreferencesStore()
        )
        let directory = makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        viewModel.selectedFolderURL = directory
        viewModel.outputDirectoryURL = directory
        viewModel.selectedDynamicRange = .hdr
        viewModel.selectedAudioLayout = .smart
        viewModel.selectedResolutionPolicy = .smart
        viewModel.selectedFrameRatePolicy = .smart
        viewModel.selectedHDRBinaryMode = .autoSystemThenBundled
        viewModel.selectedHDRHEVCEncoderMode = .automatic

        viewModel.startRender()
        await waitUntil(
            timeout: 2.0,
            message: "Timed out waiting for single render summary."
        ) {
            !viewModel.isRendering && viewModel.lastSingleRenderCompletionSummary != nil
        }

        let summary = try XCTUnwrap(viewModel.lastSingleRenderCompletionSummary)
        XCTAssertEqual(
            summary.rows.map(\.title),
            ["Container", "Codec", "HDR HEVC Encoder", "Audio", "Bitrate", "Resolution", "Frame Rate", "Range", "Engine"]
        )
        XCTAssertEqual(value(in: summary, forRowNamed: "Container"), "MP4")
        XCTAssertEqual(value(in: summary, forRowNamed: "Codec"), "HEVC")
        XCTAssertEqual(value(in: summary, forRowNamed: "HDR HEVC Encoder"), "Default (VideoToolbox)")
        XCTAssertEqual(value(in: summary, forRowNamed: "Audio"), "Smart (5.1)")
        XCTAssertEqual(value(in: summary, forRowNamed: "Bitrate"), "Balanced")
        XCTAssertEqual(value(in: summary, forRowNamed: "Resolution"), "Smart (720p)")
        XCTAssertEqual(value(in: summary, forRowNamed: "Frame Rate"), "Smart (60 fps)")
        XCTAssertEqual(value(in: summary, forRowNamed: "Range"), "HDR")
        XCTAssertEqual(value(in: summary, forRowNamed: "Engine"), "Auto (Bundled)")
        XCTAssertEqual(viewModel.renderCompleteAlertMessage, summary.alertMessage)
        XCTAssertTrue(summary.alertMessage.hasPrefix(summary.outputPath))
    }

    func testHDRHEVCEncoderSelectionPersistsAndResetRestoresDefault() {
        let preferencesStore = makePreferencesStore()
        let initialViewModel = makeViewModel(
            coordinator: RenderCoordinatorSpy(preparation: makePreparation()),
            filenameGenerator: TemporaryTestingFilenameGenerator(now: { Date(timeIntervalSince1970: 1_700_000_050) }),
            preferencesStore: preferencesStore
        )

        initialViewModel.selectedHDRHEVCEncoderMode = .videoToolbox

        let restoredViewModel = makeViewModel(
            coordinator: RenderCoordinatorSpy(preparation: makePreparation()),
            filenameGenerator: TemporaryTestingFilenameGenerator(now: { Date(timeIntervalSince1970: 1_700_000_051) }),
            preferencesStore: preferencesStore
        )

        XCTAssertEqual(restoredViewModel.selectedHDRHEVCEncoderMode, .videoToolbox)

        restoredViewModel.resetExportSettingsToPlexDefaults()

        XCTAssertEqual(restoredViewModel.selectedHDRHEVCEncoderMode, .automatic)
    }

    func testCaptureDateOverlayDefaultsToEnabled() {
        let viewModel = makeViewModel(
            coordinator: RenderCoordinatorSpy(preparation: makePreparation()),
            filenameGenerator: TemporaryTestingFilenameGenerator(now: { Date(timeIntervalSince1970: 1_700_000_060) }),
            preferencesStore: makePreferencesStore()
        )

        XCTAssertTrue(viewModel.showCaptureDateOverlay)
    }

    func testCaptureDateOverlayPersistsAcrossLaunches() {
        let preferencesStore = makePreferencesStore()
        let initialViewModel = makeViewModel(
            coordinator: RenderCoordinatorSpy(preparation: makePreparation()),
            filenameGenerator: TemporaryTestingFilenameGenerator(now: { Date(timeIntervalSince1970: 1_700_000_061) }),
            preferencesStore: preferencesStore
        )

        initialViewModel.showCaptureDateOverlay = false

        let restoredViewModel = makeViewModel(
            coordinator: RenderCoordinatorSpy(preparation: makePreparation()),
            filenameGenerator: TemporaryTestingFilenameGenerator(now: { Date(timeIntervalSince1970: 1_700_000_062) }),
            preferencesStore: preferencesStore
        )

        XCTAssertFalse(restoredViewModel.showCaptureDateOverlay)
    }

    func testCaptureDateOverlayMissingPersistedValueDefaultsToEnabled() throws {
        let preferencesStore = makePreferencesStore()
        let legacyPayload: [String: Any] = [
            "includeOpeningTitle": true,
            "openingTitleText": "June 2026",
            "crossfadeDurationSeconds": 0.75,
            "stillImageDurationSeconds": 3.0,
            "selectedPhotosFilterMode": "monthYear",
            "selectedPhotoAlbumID": "",
            "selectedContainer": "mp4",
            "selectedVideoCodec": "hevc",
            "selectedFrameRatePolicy": "smart",
            "selectedResolutionPolicy": "smart",
            "selectedDynamicRange": "hdr",
            "selectedHDRBinaryMode": "autoSystemThenBundled",
            "selectedHDRHEVCEncoderMode": "automatic",
            "selectedAudioLayout": "smart",
            "selectedBitrateMode": "balanced",
            "writeDiagnosticsLog": true
        ]
        let data = try JSONSerialization.data(withJSONObject: legacyPayload)
        preferencesStore.set(data, forKey: "MainWindowViewModel.renderSettings.v1")

        let viewModel = makeViewModel(
            coordinator: RenderCoordinatorSpy(preparation: makePreparation()),
            filenameGenerator: TemporaryTestingFilenameGenerator(now: { Date(timeIntervalSince1970: 1_700_000_063) }),
            preferencesStore: preferencesStore
        )

        XCTAssertTrue(viewModel.showCaptureDateOverlay)
    }

    func testMegaTestReusesPreparationAndIgnoresManualOutputNameField() async throws {
        let dateProvider = DateSequenceProvider([
            Date(timeIntervalSince1970: 1_700_000_000),
            Date(timeIntervalSince1970: 1_700_000_101),
            Date(timeIntervalSince1970: 1_700_000_102),
            Date(timeIntervalSince1970: 1_700_000_103),
            Date(timeIntervalSince1970: 1_700_000_104)
        ])
        let coordinator = RenderCoordinatorSpy(preparation: makePreparation())
        let viewModel = makeViewModel(
            coordinator: coordinator,
            filenameGenerator: TemporaryTestingFilenameGenerator(now: dateProvider.next),
            preferencesStore: makePreferencesStore()
        )
        let directory = makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        viewModel.selectedFolderURL = directory
        viewModel.outputDirectoryURL = directory
        viewModel.outputFilename = "Manual Override"
        viewModel.megaTestVaryResolution = true

        viewModel.startMegaTest()
        await waitUntil(
            timeout: 2.0,
            message: "Timed out waiting for mega test batch to finish."
        ) {
            coordinator.renderRequests.count == 4 && !viewModel.isRendering
        }

        XCTAssertEqual(coordinator.prepareFolderRequests.count, 1)
        XCTAssertEqual(coordinator.renderRequests.count, 4)
        XCTAssertFalse(coordinator.renderRequests.contains { $0.output.baseFilename == "Manual Override" })
        XCTAssertNil(viewModel.lastSingleRenderCompletionSummary)
        XCTAssertEqual(viewModel.renderCompleteAlertMessage, viewModel.lastOutputPath)

        let generator = TemporaryTestingFilenameGenerator()
        let expectedNames = [
            generator.makeOutputName(resolution: .fixed720p, frameRate: .smart, dynamicRange: .hdr, audioLayout: .smart, date: Date(timeIntervalSince1970: 1_700_000_101)),
            generator.makeOutputName(resolution: .fixed1080p, frameRate: .smart, dynamicRange: .hdr, audioLayout: .smart, date: Date(timeIntervalSince1970: 1_700_000_102)),
            generator.makeOutputName(resolution: .fixed4K, frameRate: .smart, dynamicRange: .hdr, audioLayout: .smart, date: Date(timeIntervalSince1970: 1_700_000_103)),
            generator.makeOutputName(resolution: .smart, frameRate: .smart, dynamicRange: .hdr, audioLayout: .smart, date: Date(timeIntervalSince1970: 1_700_000_104))
        ]

        XCTAssertEqual(coordinator.renderRequests.map { $0.output.baseFilename }, expectedNames)
    }

    func testOutputNameAutoSyncUpdatesWhenAudioChanges() {
        let viewModel = makeViewModel(
            coordinator: RenderCoordinatorSpy(preparation: makePreparation()),
            filenameGenerator: TemporaryTestingFilenameGenerator(now: { Date(timeIntervalSince1970: 1_700_000_400) }),
            preferencesStore: makePreferencesStore()
        )

        viewModel.selectedAudioLayout = .surround51

        XCTAssertTrue(viewModel.isOutputNameAutoManaged)
        XCTAssertEqual(viewModel.outputFilename, "Testing - S2026E1700000400 - Smart - Smartfps - HDR - 5.1")
    }

    func testMegaTestAudioAxisExpandsGeneratedNames() async {
        let dateProvider = DateSequenceProvider([
            Date(timeIntervalSince1970: 1_700_000_500),
            Date(timeIntervalSince1970: 1_700_000_501),
            Date(timeIntervalSince1970: 1_700_000_502),
            Date(timeIntervalSince1970: 1_700_000_503),
            Date(timeIntervalSince1970: 1_700_000_504)
        ])
        let coordinator = RenderCoordinatorSpy(preparation: makePreparation())
        let viewModel = makeViewModel(
            coordinator: coordinator,
            filenameGenerator: TemporaryTestingFilenameGenerator(now: dateProvider.next),
            preferencesStore: makePreferencesStore()
        )
        let directory = makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        viewModel.selectedFolderURL = directory
        viewModel.outputDirectoryURL = directory
        viewModel.megaTestVaryAudio = true

        viewModel.startMegaTest()
        await waitUntil(
            timeout: 2.0,
            message: "Timed out waiting for audio mega test batch to finish."
        ) {
            coordinator.renderRequests.count == 4 && !viewModel.isRendering
        }

        XCTAssertEqual(
            coordinator.renderRequests.map(\.output.baseFilename),
            [
                "Testing - S2026E1700000501 - Smart - Smartfps - HDR - Mono",
                "Testing - S2026E1700000502 - Smart - Smartfps - HDR - Stereo",
                "Testing - S2026E1700000503 - Smart - Smartfps - HDR - 5.1",
                "Testing - S2026E1700000504 - Smart - Smartfps - HDR - Smart"
            ]
        )
    }

    func testMegaTestForcesVideoToolboxForHDRHEVCWithoutChangingSelection() async {
        let dateProvider = DateSequenceProvider([
            Date(timeIntervalSince1970: 1_700_000_700),
            Date(timeIntervalSince1970: 1_700_000_701),
            Date(timeIntervalSince1970: 1_700_000_702),
            Date(timeIntervalSince1970: 1_700_000_703),
            Date(timeIntervalSince1970: 1_700_000_704)
        ])
        let coordinator = RenderCoordinatorSpy(preparation: makePreparation())
        let viewModel = makeViewModel(
            coordinator: coordinator,
            filenameGenerator: TemporaryTestingFilenameGenerator(now: dateProvider.next),
            preferencesStore: makePreferencesStore()
        )
        let directory = makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        viewModel.selectedFolderURL = directory
        viewModel.outputDirectoryURL = directory
        viewModel.selectedDynamicRange = .hdr
        viewModel.selectedHDRHEVCEncoderMode = .automatic
        viewModel.megaTestVaryAudio = true

        viewModel.startMegaTest()
        await waitUntil(
            timeout: 2.0,
            message: "Timed out waiting for HDR HEVC mega test batch to finish."
        ) {
            coordinator.renderRequests.count == 4 && !viewModel.isRendering
        }

        XCTAssertEqual(viewModel.selectedHDRHEVCEncoderMode, .automatic)
        XCTAssertEqual(
            Set(coordinator.renderRequests.map(\.export.hdrHEVCEncoderMode)),
            [.videoToolbox]
        )
    }

    func testMegaTestCanStopAfterFailure() async throws {
        let coordinator = RenderCoordinatorSpy(preparation: makePreparation(), failedRenderIndices: [0])
        let viewModel = makeViewModel(
            coordinator: coordinator,
            filenameGenerator: TemporaryTestingFilenameGenerator(now: { Date(timeIntervalSince1970: 1_700_000_200) }),
            preferencesStore: makePreferencesStore()
        )
        let directory = makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        viewModel.selectedFolderURL = directory
        viewModel.outputDirectoryURL = directory
        viewModel.megaTestVaryRange = true

        viewModel.startMegaTest()
        await waitUntilFailurePrompt(viewModel)
        viewModel.stopMegaTestAfterFailure()
        await waitUntil(
            timeout: 2.0,
            message: "Timed out waiting for mega test stop flow to finish."
        ) {
            coordinator.renderRequests.count == 1 && !viewModel.isRendering
        }

        XCTAssertEqual(coordinator.renderRequests.count, 1)
        XCTAssertNil(viewModel.pendingMegaTestFailure)
        XCTAssertFalse(viewModel.showRenderCompleteAlert)
        XCTAssertTrue(viewModel.statusMessage.contains("Mega test stopped after failure"))
    }

    func testMegaTestCanContinueAfterFailure() async throws {
        let coordinator = RenderCoordinatorSpy(preparation: makePreparation(), failedRenderIndices: [0])
        let viewModel = makeViewModel(
            coordinator: coordinator,
            filenameGenerator: TemporaryTestingFilenameGenerator(now: { Date(timeIntervalSince1970: 1_700_000_300) }),
            preferencesStore: makePreferencesStore()
        )
        let directory = makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        viewModel.selectedFolderURL = directory
        viewModel.outputDirectoryURL = directory
        viewModel.megaTestVaryRange = true

        viewModel.startMegaTest()
        await waitUntilFailurePrompt(viewModel)
        viewModel.continueMegaTestAfterFailure()
        await waitUntil(
            timeout: 2.0,
            message: "Timed out waiting for mega test continue flow to finish."
        ) {
            coordinator.renderRequests.count == 2 && !viewModel.isRendering
        }

        XCTAssertEqual(coordinator.renderRequests.count, 2)
        XCTAssertNil(viewModel.pendingMegaTestFailure)
        XCTAssertTrue(viewModel.showRenderCompleteAlert)
        XCTAssertTrue(viewModel.statusMessage.contains("Mega test complete"))
    }

    func testSingleRenderCompletionSummaryUsesRenderStartSnapshot() async throws {
        let preparation = makePreparation(
            items: [
                makeVideoItem(
                    id: "video-2",
                    pixelSize: CGSize(width: 1280, height: 720),
                    sourceFrameRate: 60,
                    sourceAudioChannelCount: 2
                )
            ]
        )
        let coordinator = RenderCoordinatorSpy(
            preparation: preparation,
            suspendRenderUntilResumed: true,
            renderResultBuilder: { _, request, _ in
                let outputURL = request.output.directory
                    .appendingPathComponent(request.output.baseFilename)
                    .appendingPathExtension(request.export.container.fileExtension)
                return RenderResult(
                    outputURL: outputURL,
                    diagnosticsLogURL: nil,
                    backendSummary: "FFmpeg HDR backend [system] (encoder: libx265)",
                    backendInfo: RenderBackendInfo(binarySource: .system, encoder: "libx265"),
                    resolvedVideoInfo: ResolvedRenderVideoInfo(width: 1920, height: 1080, frameRate: 60)
                )
            }
        )
        let viewModel = makeViewModel(
            coordinator: coordinator,
            filenameGenerator: TemporaryTestingFilenameGenerator(now: { Date(timeIntervalSince1970: 1_700_001_200) }),
            preferencesStore: makePreferencesStore()
        )
        let directory = makeTemporaryDirectory()
        defer { try? FileManager.default.removeItem(at: directory) }

        viewModel.selectedFolderURL = directory
        viewModel.outputDirectoryURL = directory
        viewModel.selectedDynamicRange = .hdr
        viewModel.selectedAudioLayout = .smart
        viewModel.selectedResolutionPolicy = .smart
        viewModel.selectedFrameRatePolicy = .smart
        viewModel.selectedHDRBinaryMode = .autoSystemThenBundled
        viewModel.selectedHDRHEVCEncoderMode = .automatic

        viewModel.startRender()
        await waitUntil(
            timeout: 2.0,
            message: "Timed out waiting for render request to start."
        ) {
            coordinator.renderRequests.count == 1
        }

        viewModel.selectedVideoCodec = .hevc
        viewModel.selectedAudioLayout = .mono
        viewModel.selectedResolutionPolicy = .fixed4K
        viewModel.selectedFrameRatePolicy = .fps30
        viewModel.selectedHDRBinaryMode = .bundledOnly
        viewModel.selectedHDRHEVCEncoderMode = .videoToolbox

        coordinator.resumeRender()
        await waitUntil(
            timeout: 2.0,
            message: "Timed out waiting for suspended render to finish."
        ) {
            !viewModel.isRendering && viewModel.lastSingleRenderCompletionSummary != nil
        }

        let summary = try XCTUnwrap(viewModel.lastSingleRenderCompletionSummary)
        XCTAssertEqual(value(in: summary, forRowNamed: "Codec"), "HEVC")
        XCTAssertEqual(value(in: summary, forRowNamed: "HDR HEVC Encoder"), "Default (libx265)")
        XCTAssertEqual(value(in: summary, forRowNamed: "Audio"), "Smart (Stereo)")
        XCTAssertEqual(value(in: summary, forRowNamed: "Resolution"), "Smart (1080p)")
        XCTAssertEqual(value(in: summary, forRowNamed: "Frame Rate"), "Smart (60 fps)")
        XCTAssertEqual(value(in: summary, forRowNamed: "Engine"), "Auto (System)")
    }

    private func makeViewModel(
        coordinator: RenderCoordinating,
        filenameGenerator: TemporaryTestingFilenameGenerator,
        preferencesStore: UserDefaults
    ) -> MainWindowViewModel {
        MainWindowViewModel(
            coordinator: coordinator,
            preferencesStore: preferencesStore,
            filenameGenerator: filenameGenerator
        )
    }

    private func makePreparation(items: [MediaItem]? = nil) -> RenderPreparation {
        let resolvedItems = items ?? [makeImageItem()]
        let style = StyleProfile.stageOneDefault
        let timeline = TimelineBuilder().buildTimeline(
            items: resolvedItems,
            ordering: .captureDateAscendingStable,
            style: style
        )
        return RenderPreparation(items: resolvedItems, timeline: timeline, warnings: [])
    }

    private func makeImageItem(
        id: String = "image",
        pixelSize: CGSize = CGSize(width: 1920, height: 1080)
    ) -> MediaItem {
        MediaItem(
            id: id,
            type: .image,
            captureDate: Date(),
            duration: nil,
            pixelSize: pixelSize,
            colorInfo: .unknown,
            locator: .file(URL(fileURLWithPath: "/tmp/\(id).jpg")),
            fileSizeBytes: 1_000,
            filename: "\(id).jpg"
        )
    }

    private func makeVideoItem(
        id: String,
        pixelSize: CGSize,
        sourceFrameRate: Double?,
        sourceAudioChannelCount: Int?
    ) -> MediaItem {
        MediaItem(
            id: id,
            type: .video,
            captureDate: Date(),
            duration: CMTime(seconds: 4, preferredTimescale: 600),
            sourceFrameRate: sourceFrameRate,
            sourceAudioChannelCount: sourceAudioChannelCount,
            pixelSize: pixelSize,
            colorInfo: .unknown,
            locator: .file(URL(fileURLWithPath: "/tmp/\(id).mov")),
            fileSizeBytes: 10_000,
            filename: "\(id).mov"
        )
    }

    private func makePreferencesStore() -> UserDefaults {
        let suiteName = "MainWindowViewModelTests.\(UUID().uuidString)"
        let defaults = UserDefaults(suiteName: suiteName) ?? .standard
        defaults.removePersistentDomain(forName: suiteName)
        return defaults
    }

    private func makeTemporaryDirectory() -> URL {
        let directory = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString, isDirectory: true)
        try? FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        return directory
    }

    private func waitUntil(
        timeout: TimeInterval = 2.0,
        message: String,
        condition: @escaping () -> Bool
    ) async {
        let deadline = Date().addingTimeInterval(timeout)
        while !condition() && Date() < deadline {
            try? await Task.sleep(for: .milliseconds(10))
        }
        XCTAssertTrue(condition(), message)
    }

    private func waitUntilFailurePrompt(_ viewModel: MainWindowViewModel, timeout: TimeInterval = 2.0) async {
        let deadline = Date().addingTimeInterval(timeout)
        while viewModel.pendingMegaTestFailure == nil && Date() < deadline {
            try? await Task.sleep(for: .milliseconds(10))
        }
        XCTAssertNotNil(viewModel.pendingMegaTestFailure, "Timed out waiting for mega test failure prompt.")
    }

    private func value(
        in summary: MainWindowViewModel.RenderCompletionSummary,
        forRowNamed title: String,
        file: StaticString = #filePath,
        line: UInt = #line
    ) -> String {
        guard let row = summary.rows.first(where: { $0.title == title }) else {
            XCTFail("Missing summary row named \(title)", file: file, line: line)
            return ""
        }
        return row.displayValue
    }
}

@MainActor
private final class RenderCoordinatorSpy: RenderCoordinating, @unchecked Sendable {
    let preparation: RenderPreparation
    let failedRenderIndices: Set<Int>
    let suspendRenderUntilResumed: Bool
    let renderResultBuilder: ((RenderPreparation, RenderRequest, Int) -> RenderResult)?
    private(set) var prepareFolderRequests: [RenderRequest] = []
    private(set) var renderRequests: [RenderRequest] = []
    private(set) var cancelCurrentRenderCallCount: Int = 0
    private var suspendedRenderContinuation: CheckedContinuation<Void, Never>?

    init(
        preparation: RenderPreparation,
        failedRenderIndices: Set<Int> = [],
        suspendRenderUntilResumed: Bool = false,
        renderResultBuilder: ((RenderPreparation, RenderRequest, Int) -> RenderResult)? = nil
    ) {
        self.preparation = preparation
        self.failedRenderIndices = failedRenderIndices
        self.suspendRenderUntilResumed = suspendRenderUntilResumed
        self.renderResultBuilder = renderResultBuilder
    }

    func prepareFolderRender(request: RenderRequest) async throws -> RenderPreparation {
        prepareFolderRequests.append(request)
        return preparation
    }

    func prepareFromItems(
        _ items: [MediaItem],
        request: RenderRequest,
        additionalWarnings: [String]
    ) -> RenderPreparation {
        RenderPreparation(
            items: items,
            timeline: preparation.timeline,
            warnings: preparation.warnings + additionalWarnings
        )
    }

    func render(
        preparation: RenderPreparation,
        request: RenderRequest,
        photoMaterializer: PhotoAssetMaterializing?,
        writeDiagnosticsLog: Bool,
        progressHandler: RenderProgressHandler,
        statusHandler: RenderStatusHandler
    ) async throws -> RenderResult {
        let index = renderRequests.count
        renderRequests.append(request)
        statusHandler?(writeDiagnosticsLog ? "Encoding with diagnostics" : "Encoding")
        progressHandler?(1.0)

        if suspendRenderUntilResumed {
            await withCheckedContinuation { continuation in
                suspendedRenderContinuation = continuation
            }
        }

        if failedRenderIndices.contains(index) {
            throw RenderError.exportFailed("Simulated failure \(index)")
        }

        let outputURL = request.output.directory
            .appendingPathComponent(request.output.baseFilename)
            .appendingPathExtension(request.export.container.fileExtension)
        if let renderResultBuilder {
            return renderResultBuilder(preparation, request, index)
        }
        return RenderResult(
            outputURL: outputURL,
            diagnosticsLogURL: nil,
            backendSummary: nil,
            backendInfo: RenderBackendInfo(
                binarySource: defaultBinarySource(for: request.export.hdrFFmpegBinaryMode),
                encoder: defaultEncoder(for: request.export)
            ),
            resolvedVideoInfo: ResolvedRenderVideoInfo(
                width: defaultVideoDimensions(for: request.export.resolution).width,
                height: defaultVideoDimensions(for: request.export.resolution).height,
                frameRate: defaultFrameRate(for: request.export.frameRate)
            )
        )
    }

    func cancelCurrentRender() {
        cancelCurrentRenderCallCount += 1
    }

    func resumeRender() {
        suspendedRenderContinuation?.resume()
        suspendedRenderContinuation = nil
    }

    private func defaultBinarySource(for mode: HDRFFmpegBinaryMode) -> RenderBackendBinarySource {
        switch mode {
        case .autoSystemThenBundled, .systemOnly:
            return .system
        case .bundledOnly:
            return .bundled
        }
    }

    private func defaultFrameRate(for policy: FrameRatePolicy) -> Int {
        switch policy {
        case .fps30, .smart:
            return 30
        case .fps60:
            return 60
        }
    }

    private func defaultEncoder(for profile: ExportProfile) -> String? {
        switch (profile.dynamicRange, profile.videoCodec, profile.hdrHEVCEncoderMode) {
        case (.hdr, .hevc, .videoToolbox):
            return "hevcVideoToolbox"
        case (.hdr, .hevc, .automatic):
            return "libx265"
        case (.sdr, .hevc, _):
            return "hevcVideoToolbox"
        case (.sdr, .h264, _), (.hdr, .h264, _):
            return "h264VideoToolbox"
        }
    }

    private func defaultVideoDimensions(for policy: ResolutionPolicy) -> (width: Int, height: Int) {
        switch policy.normalized {
        case .fixed720p:
            return (1280, 720)
        case .fixed1080p, .smart:
            return (1920, 1080)
        case .fixed4K:
            return (3840, 2160)
        case .matchSourceMax:
            return (1920, 1080)
        }
    }
}

private final class DateSequenceProvider: @unchecked Sendable {
    private let lock = NSLock()
    private var dates: [Date]

    init(_ dates: [Date]) {
        self.dates = dates
    }

    func next() -> Date {
        lock.lock()
        defer { lock.unlock() }
        guard !dates.isEmpty else {
            return Date(timeIntervalSince1970: 0)
        }
        if dates.count == 1 {
            return dates[0]
        }
        return dates.removeFirst()
    }
}
