import Core
import Foundation
import Photos
import PhotosIntegration
import SwiftUI
#if canImport(AppKit)
import AppKit
#endif

typealias RenderProgressHandler = (@MainActor @Sendable (Double) -> Void)?
typealias RenderStatusHandler = (@MainActor @Sendable (String) -> Void)?

@MainActor
protocol RenderCoordinating: AnyObject, Sendable {
    func prepareFolderRender(request: RenderRequest) async throws -> RenderPreparation
    func prepareFromItems(
        _ items: [MediaItem],
        request: RenderRequest,
        additionalWarnings: [String]
    ) -> RenderPreparation
    func render(
        preparation: RenderPreparation,
        request: RenderRequest,
        photoMaterializer: PhotoAssetMaterializing?,
        writeDiagnosticsLog: Bool,
        progressHandler: RenderProgressHandler,
        statusHandler: RenderStatusHandler
    ) async throws -> RenderResult
    func cancelCurrentRender()
}

extension RenderCoordinator: RenderCoordinating {}

@MainActor
final class MainWindowViewModel: ObservableObject {
    enum SourceMode: String, CaseIterable, Identifiable {
        case folder
        case photos

        var id: String { rawValue }

        var label: String {
            switch self {
            case .folder: return "Folder"
            case .photos: return "Apple Photos"
            }
        }
    }

    enum PhotosFilterMode: String, CaseIterable, Identifiable, Codable {
        case monthYear
        case album

        var id: String { rawValue }

        var label: String {
            switch self {
            case .monthYear:
                return "Month/Year"
            case .album:
                return "Album"
            }
        }
    }

    enum ViewModelError: LocalizedError {
        case missingFolder
        case missingAlbumSelection

        var errorDescription: String? {
            switch self {
            case .missingFolder:
                return "Choose an input folder before rendering."
            case .missingAlbumSelection:
                return "Choose a Photos album before rendering."
            }
        }
    }

    struct MegaTestFailureContext: Identifiable {
        let id = UUID()
        let combination: MegaTestCombination
        let message: String

        var alertMessage: String {
            "\(combination.displayLabel)\n\n\(message)"
        }
    }

    private enum MegaTestFailureDecision {
        case continueRemaining
        case stop
    }

    private struct PreparedRenderSession {
        let source: MediaSource
        let monthYear: MonthYear?
        let style: StyleProfile
        let preparation: RenderPreparation
        let usesPhotoMaterializer: Bool
    }

    @Published var sourceMode: SourceMode = .folder {
        didSet { refreshPhotoAlbumsIfNeeded() }
    }
    @Published var selectedFolderURL: URL?
    @Published var recursiveScan: Bool = true

    @Published var selectedMonth: Int
    @Published var selectedYear: Int
    @Published var selectedPhotosFilterMode: PhotosFilterMode = .monthYear {
        didSet {
            handleRenderSettingChange()
            refreshPhotoAlbumsIfNeeded()
        }
    }
    @Published var selectedPhotoAlbumID: String = "" {
        didSet { handleRenderSettingChange() }
    }
    @Published private(set) var photoAlbums: [PhotoAlbumSummary] = []
    @Published private(set) var isLoadingPhotoAlbums: Bool = false
    @Published private(set) var photoAlbumsStatusMessage: String = ""

    @Published var outputDirectoryURL: URL
    @Published var outputFilename: String = "" {
        didSet { handleOutputFilenameEditedIfNeeded() }
    }
    @Published private(set) var isOutputNameAutoManaged: Bool = true

    @Published var includeOpeningTitle: Bool = true {
        didSet { handleRenderSettingChange() }
    }
    @Published var openingTitleText: String {
        didSet { handleRenderSettingChange() }
    }
    @Published var crossfadeDurationSeconds: Double = 0.75 {
        didSet { handleRenderSettingChange() }
    }
    @Published var stillImageDurationSeconds: Double = 3.0 {
        didSet { handleRenderSettingChange() }
    }

    @Published var selectedContainer: ContainerFormat = MainWindowViewModel.defaultExportProfile.container {
        didSet { handleRenderSettingChange() }
    }
    @Published var selectedVideoCodec: VideoCodec = MainWindowViewModel.defaultExportProfile.videoCodec {
        didSet { handleRenderSettingChange(enforceHDRConstraints: true) }
    }
    @Published var selectedFrameRatePolicy: FrameRatePolicy = MainWindowViewModel.defaultExportProfile.frameRate {
        didSet {
            handleRenderSettingChange()
            synchronizeAutoGeneratedOutputFilenameIfNeeded()
        }
    }
    @Published var selectedResolutionPolicy: ResolutionPolicy = MainWindowViewModel.defaultExportProfile.resolution {
        didSet {
            handleRenderSettingChange()
            synchronizeAutoGeneratedOutputFilenameIfNeeded()
        }
    }
    @Published var selectedDynamicRange: DynamicRange = MainWindowViewModel.defaultExportProfile.dynamicRange {
        didSet {
            handleRenderSettingChange(enforceHDRConstraints: true)
            synchronizeAutoGeneratedOutputFilenameIfNeeded()
        }
    }
    @Published var selectedHDRBinaryMode: HDRFFmpegBinaryMode = MainWindowViewModel.defaultExportProfile.hdrFFmpegBinaryMode {
        didSet { handleRenderSettingChange() }
    }
    @Published var selectedAudioLayout: AudioLayout = MainWindowViewModel.defaultExportProfile.audioLayout {
        didSet {
            handleRenderSettingChange()
            synchronizeAutoGeneratedOutputFilenameIfNeeded()
        }
    }
    @Published var selectedBitrateMode: BitrateMode = MainWindowViewModel.defaultExportProfile.bitrateMode {
        didSet { handleRenderSettingChange() }
    }
    @Published var writeDiagnosticsLog: Bool = true {
        didSet { handleRenderSettingChange() }
    }

    @Published var megaTestVaryResolution: Bool = false
    @Published var megaTestVaryFrameRate: Bool = false
    @Published var megaTestVaryRange: Bool = false
    @Published var megaTestVaryAudio: Bool = false
    @Published private(set) var megaTestCurrentIndex: Int = 0
    @Published private(set) var megaTestTotalCount: Int = 0
    @Published var pendingMegaTestFailure: MegaTestFailureContext?

    @Published var isRendering: Bool = false
    @Published var progress: Double = 0
    @Published var statusMessage: String = "Idle"
    @Published var warnings: [String] = []
    @Published var lastOutputPath: String = ""
    @Published var lastDiagnosticsPath: String = ""
    @Published var lastBackendSummary: String = ""
    @Published var showRenderCompleteAlert: Bool = false

    let appVersionBuildLabel: String
    let months = Array(1...12)
    let years: [Int]

    private let coordinator: RenderCoordinating
    private let photoDiscovery: PhotoKitMediaDiscoveryService
    private let photoMaterializer: PhotoKitAssetMaterializer
    private let exportProfileManager: ExportProfileManager
    private let runReportService: RunReportService
    private let preferencesStore: UserDefaults
    private let filenameGenerator: TemporaryTestingFilenameGenerator
    private var renderTask: Task<Void, Never>?
    private var renderStatusDetail: String?
    private var currentMegaTestCombination: MegaTestCombination?
    private var megaTestFailureContinuation: CheckedContinuation<MegaTestFailureDecision, Never>?
    private var isApplyingExportConstraints = false
    private var isRestoringPersistedSettings = false
    private var isApplyingOutputFilenameProgrammatically = false

    private static let defaultExportProfile = ExportProfileManager().defaultProfile()
    private static let renderSettingsDefaultsKey = "MainWindowViewModel.renderSettings.v1"

    init(
        coordinator: RenderCoordinating = RenderCoordinator(),
        photoDiscovery: PhotoKitMediaDiscoveryService = PhotoKitMediaDiscoveryService(),
        photoMaterializer: PhotoKitAssetMaterializer = PhotoKitAssetMaterializer(),
        exportProfileManager: ExportProfileManager = ExportProfileManager(),
        runReportService: RunReportService = RunReportService(),
        preferencesStore: UserDefaults = .standard,
        filenameGenerator: TemporaryTestingFilenameGenerator = TemporaryTestingFilenameGenerator()
    ) {
        self.coordinator = coordinator
        self.photoDiscovery = photoDiscovery
        self.photoMaterializer = photoMaterializer
        self.exportProfileManager = exportProfileManager
        self.runReportService = runReportService
        self.preferencesStore = preferencesStore
        self.filenameGenerator = filenameGenerator
        appVersionBuildLabel = AppMetadata.versionBuildLabel

        let now = Date()
        let calendar = Calendar.current
        let currentYear = calendar.component(.year, from: now)
        let currentMonth = calendar.component(.month, from: now)
        selectedMonth = currentMonth
        selectedYear = currentYear
        openingTitleText = MonthYear(month: currentMonth, year: currentYear).displayLabel
        years = Array((currentYear - 15)...(currentYear + 2)).reversed()

        let moviesDirectory = FileManager.default.homeDirectoryForCurrentUser
            .appendingPathComponent("Movies", isDirectory: true)
            .appendingPathComponent("Monthly Video Generator", isDirectory: true)
        outputDirectoryURL = moviesDirectory

        applyPersistedRenderSettings()
        useAutoGeneratedOutputName()
    }

    func chooseInputFolder() {
        #if canImport(AppKit)
        let panel = NSOpenPanel()
        panel.canChooseDirectories = true
        panel.canChooseFiles = false
        panel.allowsMultipleSelection = false
        panel.prompt = "Select"
        panel.title = "Select Source Folder"

        if panel.runModal() == .OK {
            selectedFolderURL = panel.url
        }
        #endif
    }

    func chooseOutputFolder() {
        #if canImport(AppKit)
        let panel = NSOpenPanel()
        panel.canChooseDirectories = true
        panel.canChooseFiles = false
        panel.allowsMultipleSelection = false
        panel.prompt = "Select"
        panel.title = "Select Output Folder"

        if panel.runModal() == .OK, let url = panel.url {
            outputDirectoryURL = url
        }
        #endif
    }

    func useAutoGeneratedOutputName() {
        applyOutputFilename(generatedOutputName(), autoManaged: true)
    }

    var hasPhotoAlbums: Bool {
        !photoAlbums.isEmpty
    }

    func refreshPhotoAlbums() {
        Task {
            await loadPhotoAlbums(requestAuthorizationIfNeeded: true)
        }
    }

    var isHDRSelectionLocked: Bool {
        selectedDynamicRange == .hdr
    }

    var hdrSelectionLockReason: String {
        "HDR currently exports as HEVC Main10 video for Plex + Infuse playback on Apple TV 4K."
    }

    var bitrateModeDescription: String {
        "Bitrate mode controls FFmpeg encode quality, size, and speed tradeoffs for both SDR and HDR exports."
    }

    var frameRateDescription: String {
        switch selectedFrameRatePolicy {
        case .fps30:
            return "30 fps is the most compatible choice and keeps renders faster for photo-heavy slideshows."
        case .fps60:
            return "60 fps increases render time, CPU load, and file size significantly."
        case .smart:
            return "Smart exports at 30 fps unless any selected video is 50 fps or higher, then it exports at 60 fps."
        }
    }

    var photosSmartFrameRateDescription: String? {
        guard sourceMode == .photos, selectedFrameRatePolicy == .smart else {
            return nil
        }
        return "In Apple Photos mode, Smart fps may inspect/download selected videos before rendering to decide between 30 and 60 fps."
    }

    var photosSmartAudioDescription: String? {
        guard sourceMode == .photos, selectedAudioLayout == .smart else {
            return nil
        }
        return "In Apple Photos mode, Smart audio may inspect/download selected videos before rendering to choose Mono, Stereo, or 5.1."
    }

    var megaTestPhotosSmartAudioDescription: String? {
        guard sourceMode == .photos, megaTestVaryAudio else {
            return nil
        }
        return "When Mega Test includes Smart audio in Apple Photos mode, preparation may inspect/download selected videos before rendering."
    }

    var megaTestSelection: MegaTestSelection {
        MegaTestSelection(
            varyResolution: megaTestVaryResolution,
            varyFrameRate: megaTestVaryFrameRate,
            varyDynamicRange: megaTestVaryRange,
            varyAudioLayout: megaTestVaryAudio
        )
    }

    var megaTestCombinations: [MegaTestCombination] {
        megaTestSelection.expandedCombinations(
            currentResolution: selectedResolutionPolicy.normalized,
            currentFrameRate: selectedFrameRatePolicy,
            currentDynamicRange: selectedDynamicRange,
            currentAudioLayout: selectedAudioLayout
        )
    }

    var megaTestCombinationCount: Int {
        megaTestCombinations.count
    }

    var megaTestCombinationCountDescription: String {
        let count = megaTestCombinationCount
        if count == 1 {
            return "1 combination"
        }
        return "\(count) combinations"
    }

    func resetExportSettingsToPlexDefaults() {
        let profile = exportProfileManager.defaultProfile()
        isRestoringPersistedSettings = true
        selectedContainer = profile.container
        selectedVideoCodec = profile.videoCodec
        selectedFrameRatePolicy = profile.frameRate
        selectedResolutionPolicy = profile.resolution.normalized
        selectedDynamicRange = profile.dynamicRange
        selectedHDRBinaryMode = profile.hdrFFmpegBinaryMode
        selectedAudioLayout = profile.audioLayout
        selectedBitrateMode = profile.bitrateMode
        writeDiagnosticsLog = true
        isRestoringPersistedSettings = false
        enforceHDRSelectionConstraints()
        persistRenderSettings()
        synchronizeAutoGeneratedOutputFilenameIfNeeded()
        warnings = exportProfileManager.compatibilityWarnings(for: profile).map(\.message)
    }

    func startRender() {
        guard !isRendering, renderTask == nil else { return }

        let outputBaseFilename = currentSingleRenderOutputFilename()
        renderTask = Task {
            await performSingleRender(outputBaseFilename: outputBaseFilename)
            await MainActor.run {
                self.renderTask = nil
            }
        }
    }

    func startMegaTest() {
        guard !isRendering, renderTask == nil else { return }

        let combinations = megaTestCombinations
        renderTask = Task {
            await performMegaTest(combinations: combinations)
            await MainActor.run {
                self.renderTask = nil
            }
        }
    }

    func continueMegaTestAfterFailure() {
        resolveMegaTestFailureDecision(.continueRemaining)
    }

    func stopMegaTestAfterFailure() {
        resolveMegaTestFailureDecision(.stop)
    }

    func cancelRender() {
        renderTask?.cancel()
        resolveMegaTestFailureDecision(.stop)
        photoMaterializer.cancelPendingRequests()
        coordinator.cancelCurrentRender()
        statusMessage = "Cancelling render..."
    }

    func openRenderedOutputFolder() {
        #if canImport(AppKit)
        let outputPath = lastOutputPath.trimmingCharacters(in: .whitespacesAndNewlines)
        let directoryURL: URL
        if outputPath.isEmpty {
            directoryURL = outputDirectoryURL
        } else {
            directoryURL = URL(fileURLWithPath: outputPath).deletingLastPathComponent()
        }
        NSWorkspace.shared.open(directoryURL)
        #endif
    }

    private func performSingleRender(outputBaseFilename: String) async {
        beginRenderRun(status: "Preparing media...")

        do {
            let monthYear = MonthYear(month: selectedMonth, year: selectedYear)
            let style = buildStyle(for: monthYear)
            let preparedSession = try await prepareRenderSession(
                style: style,
                monthYear: monthYear,
                requiresSmartFrameRateInspection: selectedFrameRatePolicy == .smart,
                requiresSmartAudioInspection: selectedAudioLayout == .smart
            )
            let exportResolution = resolveExportProfile(
                resolution: selectedResolutionPolicy.normalized,
                frameRate: selectedFrameRatePolicy,
                dynamicRange: selectedDynamicRange,
                audioLayout: selectedAudioLayout,
                items: preparedSession.preparation.items
            )

            warnings = preparedSession.preparation.warnings + exportResolution.warnings.map(\.message)
            progress = max(progress, 0.08)
            renderStatusDetail = nil
            updateRenderingStatusMessage()

            let request = makeRenderRequest(
                preparedSession: preparedSession,
                exportProfile: exportResolution.effectiveProfile,
                outputBaseFilename: outputBaseFilename
            )
            let renderResult = try await renderSingleRequest(
                preparedSession: preparedSession,
                request: request,
                progressMapper: { $0 }
            )

            recordSuccessfulRender(
                renderResult,
                request: request,
                preparation: preparedSession.preparation
            )
            finishSuccessfulRun(status: "Render complete")
        } catch {
            finishFailedRun(error)
        }
    }

    private func performMegaTest(combinations: [MegaTestCombination]) async {
        beginRenderRun(status: "Preparing mega test media...")
        megaTestTotalCount = combinations.count

        do {
            let monthYear = MonthYear(month: selectedMonth, year: selectedYear)
            let style = buildStyle(for: monthYear)
            let requiresSmartFrameRateInspection = combinations.contains { $0.frameRate == .smart }
            let requiresSmartAudioInspection = combinations.contains { $0.audioLayout == .smart }
            let preparedSession = try await prepareRenderSession(
                style: style,
                monthYear: monthYear,
                requiresSmartFrameRateInspection: requiresSmartFrameRateInspection,
                requiresSmartAudioInspection: requiresSmartAudioInspection
            )

            progress = max(progress, 0.08)
            renderStatusDetail = nil
            updateRenderingStatusMessage()

            for (index, combination) in combinations.enumerated() {
                try Task.checkCancellation()

                megaTestCurrentIndex = index + 1
                currentMegaTestCombination = combination
                let exportResolution = resolveExportProfile(
                    for: combination,
                    items: preparedSession.preparation.items
                )
                warnings = preparedSession.preparation.warnings + exportResolution.warnings.map(\.message)

                let outputBaseFilename = filenameGenerator.makeOutputName(
                    resolution: combination.resolution,
                    frameRate: combination.frameRate,
                    dynamicRange: combination.dynamicRange,
                    audioLayout: combination.audioLayout
                )
                let request = makeRenderRequest(
                    preparedSession: preparedSession,
                    exportProfile: exportResolution.effectiveProfile,
                    outputBaseFilename: outputBaseFilename
                )

                do {
                    let totalCount = Double(max(combinations.count, 1))
                    let completedCount = Double(index)
                    let renderResult = try await renderSingleRequest(
                        preparedSession: preparedSession,
                        request: request,
                        progressMapper: { reportedProgress in
                            (completedCount + min(max(reportedProgress, 0), 1)) / totalCount
                        }
                    )
                    recordSuccessfulRender(
                        renderResult,
                        request: request,
                        preparation: preparedSession.preparation
                    )
                    progress = Double(index + 1) / totalCount
                } catch is CancellationError {
                    throw CancellationError()
                } catch {
                    let decision = await promptForMegaTestFailure(
                        combination: combination,
                        error: error
                    )
                    try Task.checkCancellation()
                    switch decision {
                    case .continueRemaining:
                        continue
                    case .stop:
                        renderStatusDetail = nil
                        statusMessage = "Mega test stopped after failure\n\(combination.displayLabel)\n\(formatErrorForDisplay(error))"
                        clearMegaTestState()
                        isRendering = false
                        return
                    }
                }
            }

            finishSuccessfulRun(status: "Mega test complete")
        } catch {
            finishFailedRun(error)
        }
    }

    private func buildStyle(for monthYear: MonthYear) -> StyleProfile {
        let openingTitle = includeOpeningTitle ? resolvedOpeningTitle(for: monthYear) : nil
        return StyleProfile(
            openingTitle: openingTitle,
            titleDurationSeconds: includeOpeningTitle ? 2.5 : 0,
            crossfadeDurationSeconds: crossfadeDurationSeconds,
            stillImageDurationSeconds: stillImageDurationSeconds
        )
    }

    private func currentSingleRenderOutputFilename() -> String {
        if isOutputNameAutoManaged {
            let generated = generatedOutputName()
            applyOutputFilename(generated, autoManaged: true)
            return generated
        }
        return outputFilename
    }

    private func generatedOutputName() -> String {
        filenameGenerator.makeOutputName(
            resolution: selectedResolutionPolicy.normalized,
            frameRate: selectedFrameRatePolicy,
            dynamicRange: selectedDynamicRange,
            audioLayout: selectedAudioLayout
        )
    }

    private func applyOutputFilename(_ value: String, autoManaged: Bool) {
        isApplyingOutputFilenameProgrammatically = true
        outputFilename = value
        isOutputNameAutoManaged = autoManaged
        isApplyingOutputFilenameProgrammatically = false
    }

    private func handleOutputFilenameEditedIfNeeded() {
        guard !isApplyingOutputFilenameProgrammatically else {
            return
        }
        isOutputNameAutoManaged = false
    }

    private func synchronizeAutoGeneratedOutputFilenameIfNeeded() {
        guard isOutputNameAutoManaged else {
            return
        }
        applyOutputFilename(generatedOutputName(), autoManaged: true)
    }

    private func beginRenderRun(status: String) {
        isRendering = true
        progress = 0.01
        warnings = []
        renderStatusDetail = nil
        statusMessage = status
        lastOutputPath = ""
        lastDiagnosticsPath = ""
        lastBackendSummary = ""
        showRenderCompleteAlert = false
        pendingMegaTestFailure = nil
        clearMegaTestState()
    }

    private func finishSuccessfulRun(status: String) {
        renderStatusDetail = nil
        progress = 1.0
        statusMessage = status
        if !lastDiagnosticsPath.isEmpty {
            statusMessage += "\nDiagnostics: \(lastDiagnosticsPath)"
        }
        if !lastBackendSummary.isEmpty {
            statusMessage += "\nBackend: \(lastBackendSummary)"
        }
        showRenderCompleteAlert = true
        clearMegaTestState()
        isRendering = false
    }

    private func finishFailedRun(_ error: Error) {
        renderStatusDetail = nil
        progress = 0
        statusMessage = formatErrorForDisplay(error)
        showRenderCompleteAlert = false
        pendingMegaTestFailure = nil
        clearMegaTestState()
        isRendering = false
    }

    private func clearMegaTestState() {
        megaTestCurrentIndex = 0
        megaTestTotalCount = 0
        currentMegaTestCombination = nil
    }

    private func resolveExportProfile(
        resolution: ResolutionPolicy,
        frameRate: FrameRatePolicy,
        dynamicRange: DynamicRange,
        audioLayout: AudioLayout,
        items: [MediaItem]
    ) -> ExportProfileResolution {
        exportProfileManager.resolveProfile(
            for: ExportProfile(
                container: selectedContainer,
                videoCodec: selectedVideoCodec,
                audioCodec: .aac,
                frameRate: frameRate,
                resolution: resolution.normalized,
                dynamicRange: dynamicRange,
                hdrFFmpegBinaryMode: selectedHDRBinaryMode,
                audioLayout: audioLayout,
                bitrateMode: selectedBitrateMode
            ),
            items: items
        )
    }

    private func resolveExportProfile(for combination: MegaTestCombination, items: [MediaItem]) -> ExportProfileResolution {
        resolveExportProfile(
            resolution: combination.resolution,
            frameRate: combination.frameRate,
            dynamicRange: combination.dynamicRange,
            audioLayout: combination.audioLayout,
            items: items
        )
    }

    private func prepareRenderSession(
        style: StyleProfile,
        monthYear: MonthYear,
        requiresSmartFrameRateInspection: Bool,
        requiresSmartAudioInspection: Bool
    ) async throws -> PreparedRenderSession {
        switch sourceMode {
        case .folder:
            guard let selectedFolderURL else {
                throw ViewModelError.missingFolder
            }

            let request = RenderRequest(
                source: .folder(path: selectedFolderURL, recursive: recursiveScan),
                monthYear: nil,
                ordering: .captureDateAscendingStable,
                style: style,
                export: Self.defaultExportProfile,
                output: OutputTarget(directory: outputDirectoryURL, baseFilename: outputFilename)
            )
            let preparation = try await coordinator.prepareFolderRender(request: request)
            try Task.checkCancellation()
            return PreparedRenderSession(
                source: request.source,
                monthYear: request.monthYear,
                style: style,
                preparation: preparation,
                usesPhotoMaterializer: false
            )

        case .photos:
            let status = photoDiscovery.authorizationStatus()
            if status != .authorized && status != .limited {
                let newStatus = await photoDiscovery.requestAuthorization()
                if newStatus != .authorized && newStatus != .limited {
                    throw PhotoKitDiscoveryError.unauthorized(newStatus)
                }
            }

            switch selectedPhotosFilterMode {
            case .monthYear:
                let source: MediaSource = .photosLibrary(scope: .entireLibrary(monthYear: monthYear))
                let discovered = try await photoDiscovery.discover(monthYear: monthYear)
                try Task.checkCancellation()
                let inspection = try await inspectPhotoVideosForSmartPoliciesIfNeeded(
                    discovered,
                    requiresSmartFrameRateInspection: requiresSmartFrameRateInspection,
                    requiresSmartAudioInspection: requiresSmartAudioInspection
                )
                let seedRequest = RenderRequest(
                    source: source,
                    monthYear: monthYear,
                    ordering: .captureDateAscendingStable,
                    style: style,
                    export: Self.defaultExportProfile,
                    output: OutputTarget(directory: outputDirectoryURL, baseFilename: outputFilename)
                )
                let preparation = coordinator.prepareFromItems(
                    inspection.items,
                    request: seedRequest,
                    additionalWarnings: inspection.warnings
                )
                return PreparedRenderSession(
                    source: source,
                    monthYear: monthYear,
                    style: style,
                    preparation: preparation,
                    usesPhotoMaterializer: true
                )

            case .album:
                var selectedAlbumID = selectedPhotoAlbumID.trimmingCharacters(in: .whitespacesAndNewlines)
                if selectedAlbumID.isEmpty {
                    let discoveredAlbums = try await photoDiscovery.discoverAlbums()
                    photoAlbums = discoveredAlbums
                    if let firstAlbum = discoveredAlbums.first {
                        selectedPhotoAlbumID = firstAlbum.localIdentifier
                        selectedAlbumID = firstAlbum.localIdentifier
                        photoAlbumsStatusMessage = ""
                    }
                }

                guard !selectedAlbumID.isEmpty else {
                    throw ViewModelError.missingAlbumSelection
                }

                let selectedAlbumTitle = photoAlbums.first(where: { $0.localIdentifier == selectedAlbumID })?.title
                let source: MediaSource = .photosLibrary(
                    scope: .album(localIdentifier: selectedAlbumID, title: selectedAlbumTitle))
                let discovered = try await photoDiscovery.discover(albumLocalIdentifier: selectedAlbumID)
                try Task.checkCancellation()
                let inspection = try await inspectPhotoVideosForSmartPoliciesIfNeeded(
                    discovered,
                    requiresSmartFrameRateInspection: requiresSmartFrameRateInspection,
                    requiresSmartAudioInspection: requiresSmartAudioInspection
                )
                let seedRequest = RenderRequest(
                    source: source,
                    monthYear: nil,
                    ordering: .captureDateAscendingStable,
                    style: style,
                    export: Self.defaultExportProfile,
                    output: OutputTarget(directory: outputDirectoryURL, baseFilename: outputFilename)
                )
                let preparation = coordinator.prepareFromItems(
                    inspection.items,
                    request: seedRequest,
                    additionalWarnings: inspection.warnings
                )
                return PreparedRenderSession(
                    source: source,
                    monthYear: nil,
                    style: style,
                    preparation: preparation,
                    usesPhotoMaterializer: true
                )
            }
        }
    }

    private func makeRenderRequest(
        preparedSession: PreparedRenderSession,
        exportProfile: ExportProfile,
        outputBaseFilename: String
    ) -> RenderRequest {
        RenderRequest(
            source: preparedSession.source,
            monthYear: preparedSession.monthYear,
            ordering: .captureDateAscendingStable,
            style: preparedSession.style,
            export: exportProfile,
            output: OutputTarget(directory: outputDirectoryURL, baseFilename: outputBaseFilename)
        )
    }

    private func renderSingleRequest(
        preparedSession: PreparedRenderSession,
        request: RenderRequest,
        progressMapper: @escaping @Sendable (Double) -> Double
    ) async throws -> RenderResult {
        renderStatusDetail = nil
        updateRenderingStatusMessage()
        return try await coordinator.render(
            preparation: preparedSession.preparation,
            request: request,
            photoMaterializer: preparedSession.usesPhotoMaterializer ? photoMaterializer : nil,
            writeDiagnosticsLog: writeDiagnosticsLog,
            progressHandler: { [weak self] reportedProgress in
                self?.applyReportedRenderProgress(progressMapper(reportedProgress))
            },
            statusHandler: { [weak self] status in
                self?.applyReportedRenderStatus(status)
            }
        )
    }

    private func recordSuccessfulRender(
        _ renderResult: RenderResult,
        request: RenderRequest,
        preparation: RenderPreparation
    ) {
        let outputURL = renderResult.outputURL
        let report = runReportService.makeReport(
            request: request,
            preparation: preparation,
            outputURL: outputURL,
            diagnosticsLogURL: renderResult.diagnosticsLogURL,
            renderBackendSummary: renderResult.backendSummary
        )
        let reportURL = outputURL.deletingPathExtension().appendingPathExtension("json")
        try? runReportService.write(report, to: reportURL)

        lastOutputPath = outputURL.path
        lastDiagnosticsPath = renderResult.diagnosticsLogURL?.path ?? ""
        lastBackendSummary = renderResult.backendSummary ?? ""
    }

    private func promptForMegaTestFailure(
        combination: MegaTestCombination,
        error: Error
    ) async -> MegaTestFailureDecision {
        pendingMegaTestFailure = MegaTestFailureContext(
            combination: combination,
            message: formatErrorForDisplay(error)
        )
        return await withCheckedContinuation { continuation in
            megaTestFailureContinuation = continuation
        }
    }

    private func resolveMegaTestFailureDecision(_ decision: MegaTestFailureDecision) {
        pendingMegaTestFailure = nil
        guard let continuation = megaTestFailureContinuation else {
            return
        }
        megaTestFailureContinuation = nil
        continuation.resume(returning: decision)
    }

    private func formatErrorForDisplay(_ error: Error) -> String {
        if error is CancellationError {
            return "Render cancelled"
        }

        let nsError = error as NSError
        var parts: [String] = []

        if let renderError = error as? RenderError, let description = renderError.errorDescription {
            parts.append(description)
        } else {
            parts.append("The operation could not be completed.")
        }

        parts.append("Domain: \(nsError.domain) Code: \(nsError.code)")

        if !nsError.localizedDescription.isEmpty,
           nsError.localizedDescription != "The operation could not be completed." {
            parts.append(nsError.localizedDescription)
        }

        if let reason = nsError.localizedFailureReason, !reason.isEmpty {
            parts.append("Reason: \(reason)")
        }

        if let suggestion = nsError.localizedRecoverySuggestion, !suggestion.isEmpty {
            parts.append("Suggestion: \(suggestion)")
        }

        if let underlying = nsError.userInfo[NSUnderlyingErrorKey] as? NSError {
            parts.append("Underlying: \(underlying.domain) (\(underlying.code)) \(underlying.localizedDescription)")
        }

        return parts.joined(separator: "\n")
    }

    private func inspectPhotoVideosForSmartPoliciesIfNeeded(
        _ items: [MediaItem],
        requiresSmartFrameRateInspection: Bool,
        requiresSmartAudioInspection: Bool
    ) async throws -> SmartMediaInspectionResult {
        guard requiresSmartFrameRateInspection || requiresSmartAudioInspection else {
            return SmartMediaInspectionResult(items: items, warnings: [])
        }

        return try await photoMaterializer.prepareItemsForSmartMedia(
            items,
            inspectFrameRate: requiresSmartFrameRateInspection,
            inspectAudioChannels: requiresSmartAudioInspection,
            progressHandler: { [weak self] fraction in
                Task { @MainActor in
                    guard let self else { return }
                    self.progress = max(self.progress, 0.03 + min(max(fraction, 0), 1) * 0.05)
                }
            },
            statusHandler: { [weak self] status in
                Task { @MainActor in
                    self?.statusMessage = status
                }
            }
        )
    }

    private func resolvedOpeningTitle(for monthYear: MonthYear) -> String {
        let trimmed = openingTitleText.trimmingCharacters(in: .whitespacesAndNewlines)
        if !trimmed.isEmpty {
            return trimmed
        }
        return monthYear.displayLabel
    }

    private func applyReportedRenderProgress(_ reportedProgress: Double) {
        let clamped = min(max(reportedProgress, 0), 1)
        progress = max(progress, clamped)
        updateRenderingStatusMessage()
    }

    private func applyReportedRenderStatus(_ status: String) {
        let trimmed = status.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else {
            return
        }
        renderStatusDetail = trimmed
        updateRenderingStatusMessage()
    }

    private func updateRenderingStatusMessage() {
        let percent = Int((progress * 100).rounded())
        let megaTestPrefix: String?
        if let currentMegaTestCombination,
           megaTestCurrentIndex > 0,
           megaTestTotalCount > 0 {
            megaTestPrefix = "Mega Test \(megaTestCurrentIndex)/\(megaTestTotalCount): \(currentMegaTestCombination.displayLabel)"
        } else {
            megaTestPrefix = nil
        }

        if let renderStatusDetail, !renderStatusDetail.isEmpty {
            if let megaTestPrefix {
                statusMessage = "\(megaTestPrefix)\n\(renderStatusDetail)\nOverall progress: \(percent)%"
            } else {
                statusMessage = "\(renderStatusDetail)\nOverall progress: \(percent)%"
            }
            return
        }

        if let megaTestPrefix {
            statusMessage = "\(megaTestPrefix)\nOverall progress: \(percent)%"
        } else {
            statusMessage = "Rendering... \(percent)%"
        }
    }

    private func handleRenderSettingChange(enforceHDRConstraints: Bool = false) {
        guard !isRestoringPersistedSettings else {
            return
        }
        if enforceHDRConstraints {
            enforceHDRSelectionConstraints()
        }
        persistRenderSettings()
    }

    private func refreshPhotoAlbumsIfNeeded() {
        guard sourceMode == .photos, selectedPhotosFilterMode == .album else {
            return
        }
        guard !isLoadingPhotoAlbums else {
            return
        }
        guard photoAlbums.isEmpty else {
            return
        }

        Task {
            await loadPhotoAlbums(requestAuthorizationIfNeeded: false)
        }
    }

    private func loadPhotoAlbums(requestAuthorizationIfNeeded: Bool) async {
        guard !isLoadingPhotoAlbums else {
            return
        }

        isLoadingPhotoAlbums = true
        defer { isLoadingPhotoAlbums = false }

        var status = photoDiscovery.authorizationStatus()
        if status != .authorized && status != .limited {
            if requestAuthorizationIfNeeded {
                status = await photoDiscovery.requestAuthorization()
            }
        }

        guard status == .authorized || status == .limited else {
            photoAlbums = []
            selectedPhotoAlbumID = ""
            photoAlbumsStatusMessage = "Allow Photos access to load albums."
            return
        }

        do {
            let discoveredAlbums = try await photoDiscovery.discoverAlbums()
            photoAlbums = discoveredAlbums
            if discoveredAlbums.isEmpty {
                selectedPhotoAlbumID = ""
                photoAlbumsStatusMessage = "No photo/video albums were found."
                return
            }

            if !discoveredAlbums.contains(where: { $0.localIdentifier == selectedPhotoAlbumID }) {
                selectedPhotoAlbumID = discoveredAlbums[0].localIdentifier
            }
            photoAlbumsStatusMessage = ""
        } catch {
            photoAlbums = []
            selectedPhotoAlbumID = ""
            photoAlbumsStatusMessage = error.localizedDescription
        }
    }

    private func enforceHDRSelectionConstraints() {
        guard selectedDynamicRange == .hdr else {
            return
        }
        guard !isApplyingExportConstraints else {
            return
        }

        isApplyingExportConstraints = true
        defer { isApplyingExportConstraints = false }

        if selectedVideoCodec != .hevc {
            selectedVideoCodec = .hevc
        }
    }

    private func applyPersistedRenderSettings() {
        guard let settings = loadPersistedRenderSettings() else {
            return
        }

        isRestoringPersistedSettings = true
        includeOpeningTitle = settings.includeOpeningTitle
        openingTitleText = settings.openingTitleText
        crossfadeDurationSeconds = min(max(settings.crossfadeDurationSeconds, 0), 2)
        stillImageDurationSeconds = min(max(settings.stillImageDurationSeconds, 1), 10)
        selectedPhotosFilterMode = settings.selectedPhotosFilterMode ?? .monthYear
        selectedPhotoAlbumID = settings.selectedPhotoAlbumID ?? ""
        selectedContainer = settings.selectedContainer
        selectedVideoCodec = settings.selectedVideoCodec
        selectedFrameRatePolicy = settings.selectedFrameRatePolicy ?? .smart
        selectedResolutionPolicy = settings.selectedResolutionPolicy.normalized
        selectedDynamicRange = settings.selectedDynamicRange
        selectedHDRBinaryMode = settings.selectedHDRBinaryMode ?? .autoSystemThenBundled
        selectedAudioLayout = settings.selectedAudioLayout
        selectedBitrateMode = settings.selectedBitrateMode
        writeDiagnosticsLog = settings.writeDiagnosticsLog ?? true
        isRestoringPersistedSettings = false
        enforceHDRSelectionConstraints()
        persistRenderSettings()
        refreshPhotoAlbumsIfNeeded()
    }

    private func loadPersistedRenderSettings() -> PersistedRenderSettings? {
        guard let data = preferencesStore.data(forKey: Self.renderSettingsDefaultsKey) else {
            return nil
        }
        return try? JSONDecoder().decode(PersistedRenderSettings.self, from: data)
    }

    private func persistRenderSettings() {
        let settings = PersistedRenderSettings(
            includeOpeningTitle: includeOpeningTitle,
            openingTitleText: openingTitleText,
            crossfadeDurationSeconds: crossfadeDurationSeconds,
            stillImageDurationSeconds: stillImageDurationSeconds,
            selectedPhotosFilterMode: selectedPhotosFilterMode,
            selectedPhotoAlbumID: selectedPhotoAlbumID,
            selectedContainer: selectedContainer,
            selectedVideoCodec: selectedVideoCodec,
            selectedFrameRatePolicy: selectedFrameRatePolicy,
            selectedResolutionPolicy: selectedResolutionPolicy.normalized,
            selectedDynamicRange: selectedDynamicRange,
            selectedHDRBinaryMode: selectedHDRBinaryMode,
            selectedAudioLayout: selectedAudioLayout,
            selectedBitrateMode: selectedBitrateMode,
            writeDiagnosticsLog: writeDiagnosticsLog
        )

        guard let data = try? JSONEncoder().encode(settings) else {
            return
        }
        preferencesStore.set(data, forKey: Self.renderSettingsDefaultsKey)
    }

    private struct PersistedRenderSettings: Codable {
        let includeOpeningTitle: Bool
        let openingTitleText: String
        let crossfadeDurationSeconds: Double
        let stillImageDurationSeconds: Double
        let selectedPhotosFilterMode: PhotosFilterMode?
        let selectedPhotoAlbumID: String?
        let selectedContainer: ContainerFormat
        let selectedVideoCodec: VideoCodec
        let selectedFrameRatePolicy: FrameRatePolicy?
        let selectedResolutionPolicy: ResolutionPolicy
        let selectedDynamicRange: DynamicRange
        let selectedHDRBinaryMode: HDRFFmpegBinaryMode?
        let selectedAudioLayout: AudioLayout
        let selectedBitrateMode: BitrateMode
        let writeDiagnosticsLog: Bool?
    }
}
