import Core
import SwiftUI

struct MainWindowExportPane: View {
    @ObservedObject var viewModel: MainWindowViewModel
    @Binding var isAdvancedExportSettingsExpanded: Bool

    private let rowSpacing: CGFloat = 8

    var body: some View {
        GroupBox {
            VStack(alignment: .leading, spacing: rowSpacing) {
                TextField("Series Title", text: $viewModel.plexShowTitle)
                MainWindowCaption(text: "Used for Plex TV episode filenames and embedded MP4 metadata.")

                outputControls

                MainWindowCaption(text: viewModel.outputDirectoryURL.path)
                    .lineLimit(2)
                    .fixedSize(horizontal: false, vertical: true)
                    .textSelection(.enabled)

                MainWindowCaption(text: viewModel.outputNameAutomationDescription)

                descriptionEditor

                if viewModel.showsManualMonthYearOverride {
                    manualMonthYearOverrideSection
                }

                DisclosureGroup(
                    "Advanced Export Settings",
                    isExpanded: $isAdvancedExportSettingsExpanded
                ) {
                    advancedExportSettings
                }
            }
            .frame(maxWidth: .infinity, alignment: .leading)
        } label: {
            MainWindowSectionLabel(title: "Export", accent: MainWindowTheme.accentNavy)
        }
    }

    private var outputControls: some View {
        ViewThatFits(in: .horizontal) {
            HStack(spacing: 10) {
                TextField("Filename", text: $viewModel.outputFilename)

                Button(viewModel.isOutputNameAutoManaged ? "Regenerate" : "Use Auto Name") {
                    viewModel.useAutoGeneratedOutputName()
                }

                Button("Choose Folder…") {
                    viewModel.chooseOutputFolder()
                }
                .disabled(!viewModel.canChooseOutputFolder)

                Button("Reveal Folder") {
                    viewModel.openConfiguredOutputFolder()
                }
                .disabled(!viewModel.canOpenConfiguredOutputFolder)
            }

            VStack(alignment: .leading, spacing: rowSpacing) {
                TextField("Filename", text: $viewModel.outputFilename)

                HStack(spacing: 10) {
                    Button(viewModel.isOutputNameAutoManaged ? "Regenerate" : "Use Auto Name") {
                        viewModel.useAutoGeneratedOutputName()
                    }

                    Button("Choose Folder…") {
                        viewModel.chooseOutputFolder()
                    }
                    .disabled(!viewModel.canChooseOutputFolder)

                    Button("Reveal Folder") {
                        viewModel.openConfiguredOutputFolder()
                    }
                    .disabled(!viewModel.canOpenConfiguredOutputFolder)
                }
            }
        }
    }

    private var descriptionEditor: some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack(spacing: 10) {
                Text("Description")
                    .font(.caption)
                    .foregroundStyle(.secondary)

                Spacer(minLength: 8)

                Button(viewModel.isPlexDescriptionAutoManaged ? "Regenerate" : "Use Default") {
                    viewModel.useDefaultPlexDescription()
                }
            }

            TextEditor(text: $viewModel.plexDescriptionText)
                .font(.body)
                .frame(minHeight: 84)

            MainWindowCaption(text: viewModel.plexDescriptionAutomationDescription)
        }
    }

    private var manualMonthYearOverrideSection: some View {
        VStack(alignment: .leading, spacing: rowSpacing) {
            Text("Manual Month/Year Override")
                .font(.subheadline)
                .fontWeight(.medium)
            MainWindowCaption(text: viewModel.manualMonthYearOverrideMessage)

            ViewThatFits(in: .horizontal) {
                HStack(spacing: 10) {
                    Picker("Month", selection: $viewModel.manualMonthYearOverrideMonth) {
                        ForEach(viewModel.months, id: \.self) { month in
                            Text(viewModel.monthLabel(for: month)).tag(month)
                        }
                    }

                    Picker("Year", selection: $viewModel.manualMonthYearOverrideYear) {
                        ForEach(viewModel.years, id: \.self) { year in
                            Text(String(year)).tag(year)
                        }
                    }

                    Button("Clear Override") {
                        viewModel.clearManualMonthYearOverride()
                    }
                }

                VStack(alignment: .leading, spacing: rowSpacing) {
                    Picker("Month", selection: $viewModel.manualMonthYearOverrideMonth) {
                        ForEach(viewModel.months, id: \.self) { month in
                            Text(viewModel.monthLabel(for: month)).tag(month)
                        }
                    }

                    Picker("Year", selection: $viewModel.manualMonthYearOverrideYear) {
                        ForEach(viewModel.years, id: \.self) { year in
                            Text(String(year)).tag(year)
                        }
                    }

                    Button("Clear Override") {
                        viewModel.clearManualMonthYearOverride()
                    }
                }
            }

            MainWindowCaption(text: "Use this only when folder or album media spans multiple months or is missing capture dates.")
        }
    }

    private var advancedExportSettings: some View {
        VStack(alignment: .leading, spacing: rowSpacing) {
            Grid(alignment: .leading, horizontalSpacing: 10, verticalSpacing: rowSpacing) {
                GridRow {
                    Picker("Container", selection: $viewModel.selectedContainer) {
                        ForEach(ContainerFormat.allCases, id: \.self) { format in
                            Text(format.rawValue.uppercased()).tag(format)
                        }
                    }

                    Picker("Codec", selection: $viewModel.selectedVideoCodec) {
                        ForEach(VideoCodec.allCases, id: \.self) { codec in
                            Text(codec.rawValue.uppercased()).tag(codec)
                        }
                    }
                    .disabled(viewModel.isHDRSelectionLocked)
                }

                GridRow {
                    Picker("Audio", selection: $viewModel.selectedAudioLayout) {
                        ForEach(AudioLayout.allCases, id: \.self) { layout in
                            Text(layout.displayLabel).tag(layout)
                        }
                    }

                    Picker("Bitrate", selection: $viewModel.selectedBitrateMode) {
                        ForEach(BitrateMode.allCases, id: \.self) { mode in
                            Text(mode.rawValue.capitalized).tag(mode)
                        }
                    }
                }

                GridRow {
                    Picker("Resolution", selection: $viewModel.selectedResolutionPolicy) {
                        Text("720p").tag(ResolutionPolicy.fixed720p)
                        Text("1080p").tag(ResolutionPolicy.fixed1080p)
                        Text("4K").tag(ResolutionPolicy.fixed4K)
                        Text("Smart").tag(ResolutionPolicy.smart)
                    }

                    Picker("Frame Rate", selection: $viewModel.selectedFrameRatePolicy) {
                        Text("30 fps").tag(FrameRatePolicy.fps30)
                        Text("60 fps").tag(FrameRatePolicy.fps60)
                        Text("Smart").tag(FrameRatePolicy.smart)
                    }
                }

                GridRow {
                    Picker("Range", selection: $viewModel.selectedDynamicRange) {
                        ForEach(DynamicRange.allCases, id: \.self) { range in
                            Text(range.rawValue.uppercased()).tag(range)
                        }
                    }
                    Color.clear
                }
            }

            Picker("HDR HEVC Encoder", selection: $viewModel.selectedHDRHEVCEncoderMode) {
                ForEach(HDRHEVCEncoderMode.allCases, id: \.self) { mode in
                    Text(mode.displayLabel).tag(mode)
                }
            }
            .disabled(viewModel.selectedDynamicRange != .hdr)

            Picker("HDR libx265 Speed", selection: $viewModel.selectedHDRX265Speed) {
                ForEach(HDRX265Speed.allCases, id: \.self) { speed in
                    Text(speed.displayLabel).tag(speed)
                }
            }
            .disabled(!viewModel.isHDRX265SpeedControlEnabled)

            if viewModel.isHDRSelectionLocked {
                MainWindowCaption(text: viewModel.hdrSelectionLockReason)
            }

            MainWindowCaption(text: viewModel.ffmpegEngineDescription)
            MainWindowCaption(text: viewModel.hdrHEVCEncoderDescription)
            MainWindowCaption(text: viewModel.hdrX265SpeedDescription)
            MainWindowCaption(text: viewModel.hdrX265SpeedCaution)

            VStack(alignment: .leading, spacing: 4) {
                MainWindowCaption(text: viewModel.bitrateModeDescription)
                MainWindowCaption(text: viewModel.frameRateDescription)

                if let photosSmartFrameRateDescription = viewModel.photosSmartFrameRateDescription {
                    MainWindowCaption(text: photosSmartFrameRateDescription)
                }

                if let photosSmartAudioDescription = viewModel.photosSmartAudioDescription {
                    MainWindowCaption(text: photosSmartAudioDescription)
                }
            }

            ViewThatFits(in: .horizontal) {
                HStack {
                    Toggle("Write diagnostics log (.log)", isOn: $viewModel.writeDiagnosticsLog)
                    Spacer()
                    Button("Reset to Plex Defaults") {
                        viewModel.resetExportSettingsToPlexDefaults()
                    }
                    .disabled(!viewModel.canResetExportSettings)
                }

                VStack(alignment: .leading, spacing: rowSpacing) {
                    Toggle("Write diagnostics log (.log)", isOn: $viewModel.writeDiagnosticsLog)
                    Button("Reset to Plex Defaults") {
                        viewModel.resetExportSettingsToPlexDefaults()
                    }
                    .disabled(!viewModel.canResetExportSettings)
                }
            }
        }
        .padding(.top, 4)
    }
}
